AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Globals:
  Function:
    Runtime: nodejs16.x
    CodeUri: src/functions

Resources:
  notifyEmail:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: notifyEmail.handler
  notifySms:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: notifySms.handler
